### ISSUE TITLE
MSAA artifacts

### ISSUE THREAD

**Issue by georgeouzou** [nvpro-samples/vk_order_independent_transparency#3]
It seems that using the interlock/spinlock cases with per pixel MSAA we get artifacts at the triangle edges.
To minimize these artifacts we need to have more layers than MSAA samples. For example using MSAAx8 with 4 layers produces artifacts, whereas MSAAx8 with 16 layers is okay

Tested on Geforce RTX 2070

**Comment by Triang3l** [comment]
That seems like a natural consequence of using multisampled rasterization with pixel-granularity lists. Pixels along the common edge of adjacent triangles often happen to be covered by both triangles, so they receive 2 shader invocations instead of 1 — so the list may overflow quicker along the edge, resulting in tail blending there, which looks different.

**Comment by NBickford-NV** [comment]
Yes, I believe @Triang3l 's written a good description of why this occurs: with these algorithms, increasing the number of MSAA samples increases the size of the linked lists per pixel, and makes them more likely to overflow - which produces artifacts. It would be neat if someone found a way to reduce these artifacts, though!
